Python Bot form ProgerOffline for review
YourCodeReview/review_sessions pull request #10
Opened 2021-11-11 10:01 UTC by YourCodeReview

Диаграмма:
![Screenshot_2021-11-09_00-56-06 - Proger Offline](https://user-images.githubusercontent.com/91138892/141278498-7b5a5b7d-e620-4c79-a8dc-b25badbba9ce.png)

**Описание:**
Телеграмм бот, для простых пользователей. Простонький проект который можно усложнять. На данном этапе возможно только создать свою клавиатуру ( так которая отображается внизу, под клавиатурой ). Так же можно настроить какое сообщение будет отправлятся при нажатии на кнопку. При написании использовал фреймворк aiogram и базу данные sqlite3

**Хочет получить фидбэк на:**
Очень хочe получить анализ моего ООП, так как я думаю что все костыльно. Но пока не располагаю информацией как сделать лучше. Так же реализация с базой данных, такой вариант приемлимы? Ведь в sqlite3 нет нескольких сессий.

**Вопросы ревьюерам:**
Стоит ли разделять callback'и? Или способ с условиями приемлем? Является ли реализация класса DatabaseManager нормальной?

2021-11-11 11:06 UTC, saintbyte commented on Python/ReviewSession9/customButtonsBot/bot.py
> +    def start(self):
может main ?

2021-11-11 11:34 UTC, ProgerOffline commented on Python/ReviewSession9/customButtonsBot/bot.py
> +TOKEN = "1614502276:AAFGR_oVKF89-KyrZDKrO5ryeF24yf8Icro"
Да, про переменные окружения мне знакомы, в данный момент тупанул😅

2021-11-11 11:34 UTC, ProgerOffline commented on Python/ReviewSession9/customButtonsBot/bot.py
> +    def start(self):
А разница?

2021-11-12 01:53 UTC, ZhymabekRoman commented on Python/ReviewSession9/customButtonsBot/bot.py
> +    def start(self):
> А разница?

Согласен, разницы вообще нету

2021-11-12 01:57 UTC, ZhymabekRoman commented
> Очень хочe получить анализ моего ООП, так как я думаю что все костыльно.

Мне кажется ООП тут лишнее, я сколько писал ботов на аиограм и телебот, и не разу не использовал классы, деление функционала по файлам как по мне хватает

2021-11-12 02:08 UTC, ZhymabekRoman requested changes

2021-11-12 02:08 UTC, ZhymabekRoman commented on Python/ReviewSession9/customButtonsBot/bot.py
> +    token = "1614502276:AAFGR_oVKF89-KyrZDKrO5ryeF24yf8Icro"
Хммм, а зачем два раза инициализируете токен бота?  И да, как уже сказали выше токен лучше хранить в переменных окружениях

2021-11-12 02:08 UTC, ZhymabekRoman commented on Python/ReviewSession9/customButtonsBot/callback_handlers.py
> +                cmd = button.split(":")[1]
Мне кажется тут лучше использовать фабрики колбеков: https://mastergroosha.github.io/telegram-tutorial-2/buttons/#_5

2021-11-12 02:08 UTC, ZhymabekRoman commented on Python/ReviewSession9/customButtonsBot/database.py
> +            cursor = connect.cursor()
Уууу, а зачем вы каждый раз подключаетесь к БД? Нельзя было инициализировать подключение и курсор в `__init__`? Посмотрите мой го*нокод - https://github.com/ZhymabekRoman/PyDejavuBot/blob/master/bot/database.py

2021-11-12 07:06 UTC, ProgerOffline commented on Python/ReviewSession9/customButtonsBot/callback_handlers.py
> +                cmd = button.split(":")[1]
Учту

2021-11-12 07:09 UTC, ProgerOffline commented
> > Очень хочe получить анализ моего ООП, так как я думаю что все костыльно.
> 
> Мне кажется ООП тут лишнее, я сколько писал ботов на аиограм и телебот, и не разу не использовал классы, деление функционала по файлам как по мне хватает

Хорошо, но что на счёт базы данных. Тут будет приемлемо использовать класс?

2021-11-12 07:10 UTC, ProgerOffline commented on Python/ReviewSession9/customButtonsBot/database.py
> +            cursor = connect.cursor()
Хорошо, спасибо

2021-11-12 07:59 UTC, saintbyte commented on Python/ReviewSession9/customButtonsBot/bot.py
> +    def start(self):
Разница в том что start это по смыслу типа инициализации а по сути функция это main loop. Соотвественно пока не прочтешь весь код не поймешь что start тут главная и основная функция. вот такими мелочами отличается хороший код от плохо и никаких компромиссов потому что в результате будет один большой компромисс

2021-11-12 10:57 UTC, ProgerOffline commented on Python/ReviewSession9/customButtonsBot/bot.py
> +    def start(self):
Хорошо, спасибо

2021-11-12 10:57 UTC, ProgerOffline commented on Python/ReviewSession9/customButtonsBot/bot.py
> +    token = "1614502276:AAFGR_oVKF89-KyrZDKrO5ryeF24yf8Icro"
Окей

2021-11-18 07:15 UTC, merged