Telegram bot От Edik на ревью
YourCodeReview/review_sessions pull request #14
Opened 2021-11-11 10:11 UTC by YourCodeReview

**Описание:**
Делал первый проект свой. Это телеграм бот который выдаёт расписание в соответсвии выбранного учебного заведения(предаставленно всего 2), групп и курса.
Написано на питоне , на библиотеке aiogram.Это мой самый первый проект, пытался сделать что то полезное).
Вроде всё сказал, больше не чего)                         

**Хочет получить фидбэк на:**
архитектура, тесты, код-стайл, синтаксис и тд. (всё что можно :))

**Вопросы для ревьюеров:**
Как вообще он выглядит? Это норм или нет?

2021-11-11 11:23 UTC, EdoProgram commented
Это моё)

2021-11-11 13:18 UTC, saintbyte commented
Очень большой файл - раздели на более мелкие сущности

2021-11-11 13:52 UTC, EdoProgram commented
> Очень большой файл - раздели на более мелкие сущности

Какие части лучше разделить?

2021-11-12 01:45 UTC, ZhymabekRoman requested changes

2021-11-12 01:45 UTC, ZhymabekRoman commented on Python/ReviewSession9/TelegramBotEdik/bot11.py
> +from Tok1 import token11
Токен лучше хранить в переменных окружениях

2021-11-12 01:45 UTC, ZhymabekRoman commented on Python/ReviewSession9/TelegramBotEdik/bot11.py
> +from sqlighter import SQLighter
Вы похоже что забыли скинуть файл sqlighter, или это такой модуль?

2021-11-12 01:45 UTC, ZhymabekRoman commented on Python/ReviewSession9/TelegramBotEdik/bot11.py
> +bot = Bot(token= token11)
Стоп, что !? Почему вы два раза инициализируете экземпляр бота и диспечера? Смотрите строки 8, 9 и 13,14

2021-11-12 01:45 UTC, ZhymabekRoman commented on Python/ReviewSession9/TelegramBotEdik/bot11.py
> +    markupfunc = InlineKeyboardMarkup()
Как по мне очень плохой нейминг, лучше просто keyboard, коротко и ясно

2021-11-12 01:45 UTC, ZhymabekRoman commented on Python/ReviewSession9/TelegramBotEdik/bot11.py
> +    func1 = InlineKeyboardButton('Расписание пар',callback_data = 'func1')
Тоже самое, ужастный нейминг, особенно колбека, я бы написал timetable_btn, и коллбек timetable

2021-11-12 01:45 UTC, ZhymabekRoman commented on Python/ReviewSession9/TelegramBotEdik/bot11.py
> +    await bot.send_message(message.chat.id, 'Привет, я твой помощник в студенчиской жизни 👨🏻‍🎓\nВыбери чем тебе помочь 😉', reply_markup = markupfunc)
Отвечать юзеру можно и так, через экземпляр бота, но на будущее знайте, юзеру также можно отвечать через метод класса `await message.answer("You text here", reply_keyboard=keyboard)`

2021-11-12 01:45 UTC, ZhymabekRoman commented on Python/ReviewSession9/TelegramBotEdik/bot11.py
> +@dp.callback_query_handler(lambda c: c.data == 'func1')
Лямбда тут лишнее, можно просто `@dp.callback_query_handler(text='func1')`

2021-11-12 01:45 UTC, ZhymabekRoman commented on Python/ReviewSession9/TelegramBotEdik/bot11.py
> +    @dp.callback_query_handler(lambda c: c.data == 'but_1')
What?! Вы среьезно? Почему внутри одной функции еще одна функция? Как по мне это антипотерн, тем более в aiogram

2021-11-12 01:45 UTC, ZhymabekRoman commented on Python/ReviewSession9/TelegramBotEdik/bot11.py
> +        await bot.send_message(call.message.chat.id, 'Маркетинг/математика (09:00-10:30)\n\nРусский (10:45-12:15)\n\nМаркетинг (12:45-14:15)\n\nПсихология общения (14:30-16:00)')
Это строка выглядит очень ужастно, я бы много строчный текст хранил бы в списке, и делал бы .join перед отправкой. Ну а вообще такие данные лучше в БД хранить. Пример кода:
```python
message_text = [
    'Маркетинг/математика (09:00-10:30)',
    'Русский (10:45-12:15)',
    'Маркетинг (12:45-14:15)',
    'Психология общения (14:30-16:00)'
]
await message.answer('\n'.join(message_text))
```

2021-11-12 01:48 UTC, ZhymabekRoman commented
> Как вообще он выглядит? Это норм или нет?

Как по мне просто ужасный нейменг везде почти, ну а так норм, есть кое-какие моменты где нужно доработать

2021-11-12 11:08 UTC, EdoProgram commented
> > Как вообще он выглядит? Это норм или нет?
> 
> Как по мне просто ужасный нейменг везде почти, ну а так норм, есть кое-какие моменты где нужно доработать

Спасибо большое! Буду работать

2021-11-18 07:15 UTC, merged