С++ Анонимно на ревью
YourCodeReview/review_sessions pull request #15
Opened 2021-11-11 10:13 UTC by YourCodeReview

**Описание:**
"Еженедельное задание #4. Книжный магазин.

👉 Вот ссылка на само задание:

https://telegra.ph/Zadanie-3-Knizhnyj-magazin-10-31

2021-11-11 16:52 UTC, glumpo commented on C++/ReviewSession9/BookMarket/bookmarket.txt
> +int main() {
Одна огромная функция, делающая вообще все -- как будто давно известно, что так писать код не стоит. Мало того, код даже переносами строк не разделен на логические блоки. Читать крайне сложно.

2021-11-11 16:52 UTC, glumpo commented on C++/ReviewSession9/BookMarket/bookmarket.txt
> +	string q = "Harry Potter";
Зачем вообще было придумывать названия книг? Это безумно захламляет код, при том не дает вообще ничего, еще и названия переменных q w e r t полностью убивают читаемость. Если говорить о коде, более приближенном к реальности, нам потребуется знать не только количество, но и название книг, но тогда их нужно связывать друг с другом не просто запоминая, что переменная q хранит название первой книги, а агрегируя в одной структуре или классе.

2021-11-11 16:52 UTC, glumpo commented on C++/ReviewSession9/BookMarket/bookmarket.txt
> +	int PriceWithoutDicount;
fix typo
```suggestion
	int PriceWithoutDiscount;
```

2021-11-11 16:52 UTC, glumpo commented on C++/ReviewSession9/BookMarket/bookmarket.txt
> +	PriceWithoutDicount = (bookammount[0] + bookammount[1] + bookammount[2] + bookammount[3] + bookammount[4])*price;
Add `numeric` header for std::accumulate
```suggestion
	PriceWithoutDicount = std::accumulate(std::begin(bookammount), std::end(bookammount), 0);
```

2021-11-11 16:52 UTC, glumpo commented on C++/ReviewSession9/BookMarket/bookmarket.txt
> +	int bookammount[5];
Слова/токены в названиях переменных должны отделяться друг от друга. Обычно каждое новое слово начинают с большой буквы. Ну и опечатка, ammount -> amount. Рекомендую подключить линтер какой, чтобы он опечатки находил.
```suggestion
	int bookAmount[5];
```

Также, возможно, стоит подумать об использовании std::array/std::vector

2021-11-11 16:52 UTC, glumpo commented on C++/ReviewSession9/BookMarket/bookmarket.txt
> +	for (int i = 0; i < 5; i++) { //sort
Использовать `std::sort` гораздо лучше

2021-11-11 16:52 UTC, glumpo commented on C++/ReviewSession9/BookMarket/bookmarket.txt
> +using namespace std;
Для небольшой программы это нормально, но обычно так делать не стоит.

2021-11-11 16:52 UTC, glumpo commented on C++/ReviewSession9/BookMarket/bookmarket.txt
> +	double Packprice[5] = {8, 15.2, 21.6, 25.6, 30};
Тут можно было бы добавить комментарий, откуда взялись такие числа. Тут задание не большое, потому и так понятно, но в настоящем коде я бы удивился, увидев пять рандомных констант.

2021-11-11 16:52 UTC, glumpo commented on C++/ReviewSession9/BookMarket/bookmarket.txt
> +	double Totalprice1, Totalprice2, Totalprice; // Price with disc
Переменная объявлена, но используется только через 40+ строк кода. Это вызывает вопросы. Ну и, как уже было сказано ранее, код нужно разнести на функции, так его читать невозможно.

2021-11-11 16:52 UTC, glumpo commented on C++/ReviewSession9/BookMarket/bookmarket.txt
> +	int truebookammount[5] = { bookammount[0] , bookammount[1] , bookammount[2] , bookammount[3] , bookammount[4] };
Использование std::array избавило бы от необходимости писать такой громоздкий и многословный код. Также позволило бы обобщить его на более, чем 5 позиций. В Вашем случае задача простая, но если речь будет не о 5 книгах (что, вообще-то, уже слишком много, чтобы обрабатывать копирование каждой руками) а о, скажем, 15, Вы также будете копировать каждую позицию вручную? 

1. Вы могли бы наисать цикл
2. Вы могли бы написать свою функцию копирования
3. Вы могли бы исполбзовать готовые функции копирования из стандартной библиотеки
4. Вы могли бы использовать готовую коллекцию, поддерживающую копирование (std::array)

2021-11-12 11:25 UTC, rabestro requested changes

2021-11-12 11:25 UTC, rabestro commented on C++/ReviewSession9/BookMarket/bookmarket.txt
> +	Totalprice1 = (Packprice[0] * Pacs[0] + Packprice[1] * Pacs[1] + Packprice[2] * Pacs[2] + Packprice[3] * Pacs[3] + Packprice[4] * Pacs[4]);
Здесь алгоритм вычислений имеет сложность O(n). 
Правильный алгоритм это O(1).

Странно, что никто из ревьюверов не обратил на это внимание.

2021-11-18 07:14 UTC, merged