app__generate-Password from Albert
YourCodeReview/review_sessions pull request #35
Opened 2022-01-13 10:27 UTC by YourCodeReview

**Оригинал проекта:**
https://github.com/Albert-webJS/app__generate-Password

**Описание:**
Генератор паролей. Основная логика в файле JS. Учел фидбэк с прошлого раза и постарался избавиться от глобальных переменных на сколько это было возможно. 
Попробовал реализовать динамику на лету. Также где то смог реализовать функции callback хочу знать на сколько качественно была проделана работа и какие ошибки допустил.

**На что хочет получить фидбэк?**
Хочу полностью разобрать детали данной работы. 
Работая через элементы формы потерял читаемость кода. Хочу понять как это поправить.  Разобрать работу функций. Некоторые функции нагружены не одной задачей, нужен совет по этому поводу тоже

**Вопросы ревьюерам:**
Как оптимально сделать легким и доступным код в плане функциональности и читаемости?

2022-01-13 11:22 UTC, R1KO commented on JS/ReviewSession16/app__generate-Password/js/script.js
> +let lengthValue = document.querySelector(".length");
Подобные элементы лучше идентифицировать по ид. По классу не достаточно гибко и могут быть конфликты имен если это использовать в другом проекте.

Мне кажется было бы удобнее изолировать это всё в объект, настройками которого можно настраивать пароль для каждого случая и тогда получить изолировать код синтетического примера от рабочего кода генератора, который можно будет переиспользовать

2022-01-13 11:22 UTC, R1KO commented on JS/ReviewSession16/app__generate-Password/js/script.js
> +      array.push(codeSymbolNumber);
а зачем ложить массив в массив если по сути у вас это общий список допустимых символов, не лучше ли его распаковать и положить поэлеметно?

2022-01-13 11:22 UTC, R1KO commented on JS/ReviewSession16/app__generate-Password/js/script.js
> +    if (elementForm[1].checked) {
Вы слишком полагаетесь на очередность элементов в html. Лучше задать им всем уникальные ид

2022-01-13 11:22 UTC, R1KO commented on JS/ReviewSession16/app__generate-Password/js/script.js
> +    str += String.fromCodePoint(code);
а не лучше ли тогда это складывать в массив, который обрезать и заджоинить, или еще лучше сделать через while с условием длины. чтобы не перебирать все символы. а только нужные.

И кстати текущий алгоритм исключает попадание одинаковых символов в пароль.

2022-01-13 11:27 UTC, R1KO commented on JS/ReviewSession16/app__generate-Password/js/script.js
> +let lengthValue = document.querySelector(".length");
Что-то вроде (самый банальный пример):
```js
// находим нужные инпуты
// Получаем длину в length
// Подписываемся на клик по кнопке
btn.addEventListener("click", () => {
    numbersPassword.value = (new PasswordGenerator({numbers: true})).generate(length);
    lowerСasePassword.value = (new PasswordGenerator({lowerСaseLetters: true})).generate(length);
    upperСasePassword.value = (new PasswordGenerator({upperСase: true})).generate(length);
    anyPassword.value = (new PasswordGenerator({numbers: true, lowerСaseLetters: true, upperСase: true})).generate(length);
  });
}

```

2022-01-15 13:15 UTC, StanislavPonomarev93 commented
// форма доступна по id
// остальные элементы находятся в форме, лучше искать в ней, а не по всему документу каждый раз
const lengthValue = formGeneratePassword.querySelector('.length');
const generatePasswordButton = formGeneratePassword.querySelector('.generate_password');

const symbolCodePoint = (start, end) => [...Array(end - start)].map((_, i) => String.fromCodePoint(start + i + 1));

// Лучше чтоб они сразу генерировались и были доступны каждый рендер пароля
const codeSymbolNumber = symbolCodePoint(48, 57);
const codeSymbolLowerCase = symbolCodePoint(64, 90);
const codeSymbolUpperCase = symbolCodePoint(96, 122);


const generatePassword = (arr) => {
  let password = '';
  for (let i = formGeneratePassword.passwordLength.value; i > 0; i--) {
    password += arr[Math.floor(Math.random() * arr.length)]
  }
  return password;
}

// Лучше использовать textContent, а не innerHTML
formGeneratePassword.passwordLength.addEventListener('input', function () {
  lengthValue.textContent = `( ${this.value} )`;
});

generatePasswordButton.addEventListener('click', () => {
  let arr = [];

  // инпуты доступны через name формы, это лучше чем по индексу их брать
  if (formGeneratePassword.numbers.checked) {
    arr.push(...codeSymbolNumber)
  };
  if (formGeneratePassword.lowerCase.checked) {
    arr.push(...codeSymbolLowerCase)
  };
  if (formGeneratePassword.upperCase.checked) {
    arr.push(...codeSymbolUpperCase)
  };

  formGeneratePassword.passwordValue.value = generatePassword(arr);
});

2022-01-16 15:40 UTC, Kp0c commented on JS/ReviewSession16/app__generate-Password/js/script.js
> +  let result = [].concat(...arr);
Если честно, не совсем понимаю смысл этого приема. Если нужна неглубокая копия массива - лучше использовать `let result = [...arr]`

2022-01-17 10:57 UTC, R1KO commented on JS/ReviewSession16/app__generate-Password/js/script.js
> +  let result = [].concat(...arr);
@Kp0c это не копирование массива, а разворачивание вложенных `[[..], [...], ...] => [...]`

2022-01-17 11:13 UTC, Kp0c commented on JS/ReviewSession16/app__generate-Password/js/script.js
> +  let result = [].concat(...arr);
Ага, вижу, пропустил что передается массив массивов. Тут бы или дизайн поменять, или с именами переменных поиграться :)

2022-01-20 19:00 UTC, QoreCode requested changes
В алгоритме есть косяки
1. С настройками по умолчанию сгенерируется пароль из 36 символов. Потом он обрежется под заданную длину. Если я задал длину в 5 символов то ~85-90% процессорного времени будет потрачено в пустую
2. Если убрать все чекбоксы, то пароль не будет сгенерирован вообще)

2022-01-27 12:53 UTC, merged