Python EisAutoAcceptance form notbadcodecom на ревью
YourCodeReview/review_sessions pull request #7
Opened 2021-11-11 09:45 UTC by YourCodeReview

Это вторая часть проекта с нашей прошлой сессии.

На этот раз на ревью отдаем Parser и Report.

Описание:

Скрипт на селениуме, связывает поступившие платежи с начислениями в системе. Код любительский, хочется комментариев.

2021-11-12 06:27 UTC, rabestro requested changes

2021-11-12 06:27 UTC, rabestro commented on Python/ReviewSession9/EisAutoAcceptance/parse.py
> +        for reg in [reg for reg in os.listdir(self.regs) if reg[-4:] == ".XML"]:
Я не программирую на Python. Но здесь общая рекомендация — именовать сложные выражения.
Здесь я бы дал название списку который вы конструируете для цикла.
Пример:
```
xmlFiles = […]
for reg in xmlFiles:
```
Подобный приём значительно упрощает чтение кода.

2021-11-12 06:27 UTC, rabestro commented on Python/ReviewSession9/EisAutoAcceptance/parse.py
> +        if register.find("KBK").text == self.cfg["code"]["fine"].split(";")[0]:
Повторю — давайте имена сложным выражениям. Комментарии не нужны.
Придумайте хорошее имя которое отражает суть сложного выражения.

isSomeThing = …
if isSomeThing:

2021-11-12 06:32 UTC, notbadcodecom commented on Python/ReviewSession9/EisAutoAcceptance/parse.py
> +        for reg in [reg for reg in os.listdir(self.regs) if reg[-4:] == ".XML"]:
Справедливое замечание. Изначально примерно так и было, но линтер ругался, что по PEP8 у меня слишком много переменных.
Спасибо за замечание, учту. Тут уже вопрос организации кода.

2021-11-12 06:41 UTC, notbadcodecom commented on Python/ReviewSession9/EisAutoAcceptance/parse.py
> +        if register.find("KBK").text == self.cfg["code"]["fine"].split(";")[0]:
Ок.
А комментарии не нужны, но нужно делать описание методам, это я теперь это буду практиковать.

2021-11-12 06:43 UTC, rabestro commented on Python/ReviewSession9/EisAutoAcceptance/parse.py
> +        for reg in [reg for reg in os.listdir(self.regs) if reg[-4:] == ".XML"]:
Выражение можно вынести в метод: `xmlFiles()`

2021-11-13 10:18 UTC, saintbyte commented on Python/ReviewSession9/EisAutoAcceptance/parse.py
> +        for reg in [reg for reg in os.listdir(self.regs) if reg[-4:] == ".XML"]:
xmlFiles это не по питонячи,по питонячи xml_files

2021-11-13 17:36 UTC, amenabe22 commented
Everything looks clean one suggestion is it would be great if you can shorten the parse_pay_data method because methods like that might grow longer if you add more conditions later. 

Conditions below this
https://github.com/notbadcodecom/EisAutoAcceptance/blob/acc6b347fa4dabc2c66059fea603f382c4d720be/src/parse.py#L41

Where you can make it cleaner with a separate method like this here
https://github.com/notbadcodecom/EisAutoAcceptance/blob/acc6b347fa4dabc2c66059fea603f382c4d720be/src/report.py#L23

2021-11-13 17:39 UTC, amenabe22 commented
Don't forget to place this in a main function then call it there it's cleaner incase you add something upon startup 
https://github.com/notbadcodecom/EisAutoAcceptance/blob/acc6b347fa4dabc2c66059fea603f382c4d720be/main.py#L90

2021-11-18 07:16 UTC, merged